export const REGION_OPTIONS = [
    { value: 'us-east-1', label: 'US East (N. Virginia)', description:'us-east-1' },
    { value: 'us-east-2', label: 'US East (Ohio)', description:'us-east-2' },
    { value: 'us-west-1', label: 'US West (N. California)', description:'us-west-1' },
    { value: 'us-west-2', label: 'US West (Oregon)', description:'us-west-2' },
    { value: 'af-south-1', label: 'Africa (Cape Town)', description:'af-south-1' },
    { value: 'ap-east-1', label: 'Asia Pacific (Hong Kong)', description:'ap-east-1' },
    { value: 'ap-south-1', label: 'Asia Pacific (Mumbai)', description:'ap-south-1' },
    { value: 'ap-northeast-1', label: 'Asia Pacific (Tokyo)', description:'ap-northeast-1' },
    { value: 'ap-northeast-2', label: 'Asia Pacific (Seoul)', description:'ap-northeast-2' },
    { value: 'ap-northeast-3', label: 'Asia Pacific (Osaka)', description:'ap-northeast-3' },
    { value: 'ap-southeast-1', label: 'Asia Pacific (Singapore)', description:'ap-southeast-1' },
    { value: 'ap-southeast-2', label: 'Asia Pacific (Sydney)', description:'ap-southeast-2' },
    { value: 'ap-southeast-3', label: 'Asia Pacific (Jakarta)', description:'ap-southeast-3' },
    { value: 'ca-central-1', label: 'Canada (Central)', description:'ca-central-1' },
    { value: 'eu-central-1', label: 'Europe (Frankfurt)', description:'eu-central-1' },
    { value: 'eu-west-1', label: 'Europe (Ireland)', description:'eu-west-1' },
    { value: 'eu-west-2', label: 'Europe (London)', description:'eu-west-2' },
    { value: 'eu-west-3', label: 'Europe (Paris)', description:'eu-west-3' },
    { value: 'eu-north-1', label: 'Europe (Stockholm)', description:'eu-north-1' },
    { value: 'eu-south-1', label: 'Europe (Milan)', description:'eu-south-1' },
    { value: 'me-south-1', label: 'Middle East (Bahrain)', description:'me-south-1' },
    { value: 'sa-east-1', label: 'South America (São Paulo)', description:'sa-east-1' }
  ];